### ISSUE TITLE
Mess-up in docs

### ISSUE THREAD

**Issue by hsyyid** [NucleusPowered/nucleuspowered.github.io#2]
`[Sponge]: Error occurred while executing command 'kit onetime:shiny1 true' for source`

Docs are wrong, it's onetime kitname not ontime:kitname like it says

**Comment by dualspiral** [comment]
From http://nucleuspowered.org/docs/modules/kit.html

> To set a kit as “one use only”, run /kit onetime [kit] [true|false].

That looks OK to me, where are you seeing the mess up?
