### ISSUE TITLE
[Request] Detect Grand Economics as economy.

### ISSUE THREAD

**Issue by PrincessKimchi** [NucleusPowered/nucleuspowered.github.io#26]
Can you please add Grand Economics or ForgeEssentials Economic. If you add Grand Economics detection then it would link to Ender Pay Forge Essentials and more.

**Comment by dualspiral** [comment]
No, we support plugins that implement the Sponge Economy service. If you want that support, you need to ask someone (elsewhere) to build a plugin to bridge between the two.
